export { createVeil } from "./veil.js";
export { createHardScorer, hardScore } from "./scoring/hard.js";
export { createLinearLearnedRanker, scoreLearnedSignals } from "./scoring/learned.js";
export { retrieveCandidates, scoreItemsWithVector } from "./scoring/retrieval.js";
export { buildPluginSignalSnapshot, collectPluginSignals } from "./scoring/signals.js";
export { softRank } from "./scoring/soft.js";
export { createChatRuntime, buildSystemPrompt, resolveChatConfigDefaults, InMemoryChatRepository, createChatId, readTextStream, normalizeChatTools, resolveChatTools } from "./chat/index.js";
export {
  createBehaviorSignalPlugin,
  createFieldSignalPlugin,
  createReviewsSignalPlugin,
  createSocialSignalPlugin,
} from "./plugins/builtin.js";
export type {
  CandidateRetrievalResult,
  CandidateRetriever,
  ChatRepository,
  ChatRespondInput,
  ChatRespondResult,
  ChatConfig,
  CompleteChatRunInput,
  CreateChatRunInput,
  CreateChatThreadInput,
  CycleRunOptions,
  FailChatRunInput,
  ListChatThreadsInput,
  FeatureNormalization,
  FeatureProvider,
  FeatureStats,
  HardConfig,
  HardFeatureConfig,
  HardScoringContext,
  HardScoringOptions,
  LLMRoleConfig,
  LearnedConfig,
  LearnedFeatureSource,
  LearnedRanker,
  LinearLearnedFeature,
  LinearLearnedRankerConfig,
  PluginFeatureMap,
  PluginSignal,
  PluginSignalContext,
  PluginSignalSnapshot,
  PluginSignalValue,
  QueueAdapter,
  QueueMessage,
  RecommendationConfig,
  RetrievalConfig,
  ScoringPolicy,
  ServeFilter,
  ServeOptions,
  StatsSnapshot,
  StorageAdapter,
  UserAffinityMap,
  UserContext,
  UserInteractionHistory,
  VectorAdapter,
  VectorQuery,
  VectorScoredItem,
  VeilPlugin,
  VeilCacheItem,
  VeilChatItem,
  VeilChatMessage,
  VeilChatMessageRole,
  VeilChatRun,
  VeilChatRunStatus,
  VeilChatRuntime,
  VeilChatRuntimeContext,
  VeilChatRuntimeOptions,
  VeilChatThread,
  VeilChatThreadStatus,
  VeilChatTool,
  VeilChatToolContext,
  VeilChatToolPolicy,
  VeilChatToolProvider,
  VeilConfig,
  VeilFeedback,
  VeilItem,
  VeilLanguageModel,
  VeilRankedItem,
  VeilResultMeta,
} from "./types/index.js";
